### ISSUE TITLE
new version 5.3.0 - undefined method `arity' for

### ISSUE THREAD

**Issue by kivanio** [bootstrap-ruby/bootstrap_form#702]
After upgrade to 5.3.0 
I start to see this kind of error at CI:

```
ActionView::Template::Error undefined method `arity' for :fine_by_percentage?:Symbol
\e[1mFailure/Error: \e[0m= f.text_field :fine_percentage
```

It complains about this `if: :fine_by_percentage?` in model:

```
validates :fine_percentage, presence: true, numericality: { greater_than_or_equal_to: 0.01, less_than: 100 }, if: :fine_by_percentage?
```

**Comment by donv** [comment]
@kivanio I will take a look.

**Comment by donv** [comment]
I have found the error.  Will fix and release shortly.

**Comment by donv** [comment]
@kivanio Could you try version 5.3.1 ?

**Comment by kivanio** [comment]
@donv It is fixed.

Thank you 🙏🏻
